language: ruby
dist: xenial
group: edge

cache:
  bundler: true
  directories:
  - ${HOME}/perl5
  - ${HOME}/.cache

services:
- redis-server

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-server-dev-10

env:
  global:
  - DATABASE_URL='postgres://localhost:5432/job_board_test'
  - RUBYOPT=-W0
  matrix:
  - INTEGRATION_SPECS='1' COVERAGE='1'
  - INTEGRATION_SPECS='0'

before_install:
- gem install bundler
- script/install-sqitch
- eval "$(perl -I ~/perl5/lib/perl5/ '-Mlocal::lib')"
- psql -c 'select version()'
- gem install bundler -v 2.0.1

before_script:
- createdb job_board_test
- sqitch deploy
- sqitch verify
